/* Quid Pro Quo
 * A deduction mini-game by mausimus and joker for DOSember Game Jam 2025
 * https://github.com/mausimus/dos2025
 * MIT License
 */

#if !defined(COMMON_H)
#define COMMON_H

#define QUIZ_PAGE 1
#define SCRATCH_PAGE 2
#define SPRITE_PAGE 3

#define QUIZ_BUTTON_W 64
#define QUIZ_BUTTON_H 31

#define LINE_HEIGHT 9
#define CLUE_HEIGHT 10

#define WORD_FG 14
#define WORD_BG 1
#define QUIZ_FG 7
#define QUIZ_BG 8
#define INPUT_FG 14
#define INPUT_BG 5
#define INV_FG 14
#define INV_BG 3
#define INV_EG 0

#define POPUP_EG 8
#define POPUP_BG 15
#define POPUP_FG 0

#define POPUP_PRINT_BG 15
#define POPUP_PRINT_EG 8
#define POPUP_PRINT_FG 0

#define POPUP_HAND_BG 15
#define POPUP_HAND_EG 8
#define POPUP_HAND_FG 1

#define INV_MARGIN 104

typedef unsigned char uchar;
typedef unsigned int uint;
typedef unsigned long ulong;

#endif
